import { NextRequest, NextResponse } from 'next/server';

// ─── Types ────────────────────────────────────────────────────────────

interface HeadlineRow {
  date: string;
  bus_rkl: number;
  bus_rkn: number;
  bus_rpn: number;
  rail_lrt_ampang: number;
  rail_mrt_kajang: number;
  rail_lrt_kj: number;
  rail_monorail: number;
  rail_mrt_pjy: number;
  rail_ets: number;
  rail_intercity: number;
  rail_komuter_utara: number;
  rail_tebrau: number;
  rail_komuter: number;
}

interface KtmbDailyRow {
  date: string;
  service: string;
  ridership: number;
}

interface PrasaranaDailyRow {
  date: string;
  rail_lrt_ampang: number;
  rail_lrt_kj: number;
  rail_mrt_kajang: number;
  rail_mrt_pjy: number;
  rail_monorail: number;
  bus_rkl: number;
}

// KTMB service → headline column mapping
const KTMB_SERVICE_MAP: Record<string, keyof HeadlineRow> = {
  ets: 'rail_ets',
  intercity: 'rail_intercity',
  komuter: 'rail_komuter',
  komuter_utara: 'rail_komuter_utara',
  shuttle_tebrau: 'rail_tebrau',
};

// ─── Cache ─────────────────────────────────────────────────────────────

const CACHE_TTL_MS = 6 * 60 * 60 * 1000; // 6 hours

let cachedResponse: { data: HeadlineRow[]; timestamp: number } | null = null;

// ─── Data fetchers ────────────────────────────────────────────────────

/**
 * Fetch Prasarana per-line daily totals from pre-generated JSON.
 * Generated by `bun run generate-prasarana.js` which parses the
 * prasarana_timeseries.parquet from data.gov.my dashboard storage.
 *
 * Contains per-line breakdown: SBK, SSP, KJ, Ampang, Monorail, BRT.
 */
async function fetchPrasaranaDaily(
  startDate: string,
  origin: string
): Promise<Map<string, PrasaranaDailyRow>> {
  try {
    const res = await fetch(`${origin}/prasarana-daily-totals.json`);
    if (!res.ok) return new Map();

    const data: PrasaranaDailyRow[] = await res.json();
    const byDate = new Map<string, PrasaranaDailyRow>();

    for (const row of data) {
      if (row.date > startDate) {
        byDate.set(row.date, row);
      }
    }

    return byDate;
  } catch (err) {
    console.warn('Prasarana daily fetch failed:', err);
    return new Map();
  }
}

async function fetchKtmbDaily(
  startDate: string,
  endDate: string
): Promise<Map<string, Record<string, number>>> {
  try {
    const url = new URL('https://api.data.gov.my/data-catalogue');
    url.searchParams.set('id', 'ridership_ktmb_daily');
    url.searchParams.set('date_start', `${startDate}@date`);
    url.searchParams.set('date_end', `${endDate}@date`);

    const res = await fetch(url.toString(), {
      headers: { Accept: 'application/json' },
    });
    if (!res.ok) return new Map();

    const ktmbData: KtmbDailyRow[] = await res.json();
    const byDate = new Map<string, Record<string, number>>();

    for (const row of ktmbData) {
      if (!byDate.has(row.date)) byDate.set(row.date, {});
      const col = KTMB_SERVICE_MAP[row.service];
      if (col) byDate.get(row.date)![col] = row.ridership;
    }

    return byDate;
  } catch (err) {
    console.warn('KTMB daily fetch failed:', err);
    return new Map();
  }
}

// ─── GET handler ─────────────────────────────────────────────────────

/**
 * Returns ridership data for the date comparison feature.
 *
 * Three-tier data merge:
 *   1. Local headline-daily.json — All 14 services, 2019 → 2026-04-30 (audited monthly)
 *   2. Prasarana per-line JSON — Rapid Rail + BRT daily totals from OD parquet (pre-audit, updated ~daily)
 *   3. data.gov.my KTMB Daily API — 5 KTMB services (updated daily)
 *
 * Query params:
 *   - start_date / end_date / dates: optional filters
 *   - nocache=1: bypass in-memory cache
 */
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const startDate = searchParams.get('start_date');
  const endDate = searchParams.get('end_date');
  const datesParam = searchParams.get('dates');
  const noCache = searchParams.get('nocache') === '1';

  try {
    // Check cache
    if (
      !noCache &&
      cachedResponse &&
      Date.now() - cachedResponse.timestamp < CACHE_TTL_MS
    ) {
      const filtered = filterData(
        cachedResponse.data,
        startDate,
        endDate,
        datesParam
      );
      return NextResponse.json(buildResponse(filtered, cachedResponse.data), {
        headers: noCache
          ? { 'Cache-Control': 'no-cache' }
          : { 'Cache-Control': 'public, s-maxage=21600, stale-while-revalidate=86400' },
      });
    }

    // 1. Load base headline data from local JSON
    // Uses headline-recent.json (2024+, ~241KB) instead of full file (~736KB)
    // to reduce CPU time from JSON.parse on cold cache miss.
    const baseUrl = new URL(request.url).origin;
    const res = await fetch(`${baseUrl}/headline-recent.json`);
    if (!res.ok) {
      return NextResponse.json(
        { error: 'Failed to load headline data' },
        { status: 500, headers: { 'Cache-Control': 'no-cache' } }
      );
    }

    const data: HeadlineRow[] = await res.json();

    // 2. Determine the last date in headline data
    const headlineMaxDate = data[data.length - 1]?.date ?? '2026-04-30';
    const today = new Date().toISOString().split('T')[0];

    // 3. Fetch extension data in parallel
    const [prasaranaDaily, ktmbDaily] = await Promise.all([
      fetchPrasaranaDaily(headlineMaxDate, baseUrl),
      fetchKtmbDaily(headlineMaxDate, today),
    ]);

    // 4. Build extension rows (dates beyond headline)
    const extensionDates = new Set<string>();
    for (const d of prasaranaDaily.keys()) extensionDates.add(d);
    for (const d of ktmbDaily.keys()) extensionDates.add(d);

    const extension: HeadlineRow[] = [];
    for (const date of extensionDates) {
      const pras = prasaranaDaily.get(date);
      const ktmb = ktmbDaily.get(date) ?? {};

      extension.push({
        date,
        bus_rkl: pras?.bus_rkl ?? 0,
        bus_rkn: 0,
        bus_rpn: 0,
        rail_lrt_ampang: pras?.rail_lrt_ampang ?? 0,
        rail_mrt_kajang: pras?.rail_mrt_kajang ?? 0,
        rail_lrt_kj: pras?.rail_lrt_kj ?? 0,
        rail_monorail: pras?.rail_monorail ?? 0,
        rail_mrt_pjy: pras?.rail_mrt_pjy ?? 0,
        rail_ets: ktmb['rail_ets'] ?? 0,
        rail_intercity: ktmb['rail_intercity'] ?? 0,
        rail_komuter_utara: ktmb['rail_komuter_utara'] ?? 0,
        rail_tebrau: ktmb['rail_tebrau'] ?? 0,
        rail_komuter: ktmb['rail_komuter'] ?? 0,
      });
    }

    // 5. Merge: headline data + extension
    const merged = [...data, ...extension].sort((a, b) =>
      a.date.localeCompare(b.date)
    );

    // 6. Cache the result
    cachedResponse = { data: merged, timestamp: Date.now() };

    // 7. Filter and return
    const filtered = filterData(merged, startDate, endDate, datesParam);
    return NextResponse.json(buildResponse(filtered, merged), {
      headers: noCache
        ? { 'Cache-Control': 'no-cache' }
        : { 'Cache-Control': 'public, s-maxage=21600, stale-while-revalidate=86400' },
    });
  } catch (error) {
    console.error('Comparison data API error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch comparison data' },
      { status: 502, headers: { 'Cache-Control': 'no-cache' } }
    );
  }
}

// ─── Helpers ─────────────────────────────────────────────────────────

function filterData(
  data: HeadlineRow[],
  startDate: string | null,
  endDate: string | null,
  datesParam: string | null
): HeadlineRow[] {
  let targetDates: Set<string> | null = null;
  if (datesParam) {
    targetDates = new Set(datesParam.split(',').map((d) => d.trim()));
  }

  return data.filter((row) => {
    if (targetDates && !targetDates.has(row.date)) return false;
    if (startDate && row.date < startDate) return false;
    if (endDate && row.date > endDate) return false;
    return true;
  });
}

function buildResponse(filtered: HeadlineRow[], full: HeadlineRow[]) {
  const headlineEnd = full.findLastIndex(
    (d) =>
      d.rail_mrt_kajang > 0 ||
      d.rail_lrt_kj > 0 ||
      d.rail_lrt_ampang > 0
  );
  const headlineMax = headlineEnd >= 0 ? full[headlineEnd].date : null;

  const prasaranaEnd = full.findLastIndex(
    (d) =>
      d.rail_mrt_kajang > 0 ||
      d.rail_lrt_kj > 0 ||
      d.rail_lrt_ampang > 0 ||
      d.rail_monorail > 0 ||
      d.rail_mrt_pjy > 0
  );
  const prasaranaMax = prasaranaEnd >= 0 ? full[prasaranaEnd].date : headlineMax;

  const ktmbEnd = full.findLastIndex(
    (d) =>
      d.rail_ets > 0 ||
      d.rail_komuter > 0 ||
      d.rail_intercity > 0 ||
      d.rail_komuter_utara > 0 ||
      d.rail_tebrau > 0
  );
  const ktmbMax = ktmbEnd >= 0 ? full[ktmbEnd].date : null;

  return {
    count: filtered.length,
    date_range: {
      min: filtered[0]?.date ?? null,
      max: filtered[filtered.length - 1]?.date ?? null,
    },
    full_range: {
      min: full[0]?.date ?? null,
      max: full[full.length - 1]?.date ?? null,
      total_days: full.length,
      headline_through: headlineMax,
      prasarana_through: prasaranaMax,
      ktmb_through: ktmbMax,
    },
    data: filtered,
  };
}
