/**
 * Prasarana Real-Time Ridership Microservice
 * Port: 3020
 *
 * Serves pre-computed per-line daily Prasarana rail ridership JSON.
 * The data is generated by process_parquet.py which downloads and
 * processes the Prasarana explorer parquet from data.gov.my.
 */

import { execSync } from 'child_process';
import { readFileSync, existsSync, writeFileSync } from 'fs';
import { join } from 'path';

const CACHE_FILE = '/tmp/prasarana_daily.json';
const PARQUET_URL = 'https://storage.data.gov.my/dashboards/prasarana_timeseries.parquet';
const TMP_PARQUET = '/tmp/prasarana_timeseries.parquet';
const SCRIPT_PATH = join(import.meta.dir, 'process_parquet.py');

function refresh(): unknown[] {
  try {
    execSync(`curl -sL "${PARQUET_URL}" -o "${TMP_PARQUET}"`, { timeout: 60000 });
    execSync(`python3 "${SCRIPT_PATH}"`, { maxBuffer: 50 * 1024 * 1024, timeout: 30000 });
    if (!existsSync(CACHE_FILE)) return [];
    const result = JSON.parse(readFileSync(CACHE_FILE, 'utf-8'));
    console.log(`[refresh] ${result.length} days`);
    return result;
  } catch (e) {
    console.error('[refresh] error:', e);
    if (existsSync(CACHE_FILE)) return JSON.parse(readFileSync(CACHE_FILE, 'utf-8'));
    return [];
  }
}

let data = existsSync(CACHE_FILE) ? JSON.parse(readFileSync(CACHE_FILE, 'utf-8')) : [];

const server = Bun.serve({
  port: 3020,
  fetch(req) {
    return new Response(JSON.stringify(data), {
      headers: { 'Content-Type': 'application/json' },
    });
  },
});

console.log(`Prasarana service on :${server.port}, ${data.length} days`);

// Refresh every 30 min
setInterval(() => { data = refresh(); }, 30 * 60 * 1000);
// Also refresh on startup (async, non-blocking)
setTimeout(() => { data = refresh(); }, 2000);
